apiVersion: v1
kind: Service
metadata:
    name: dev-service

spec:
    type: NodePort
    ports:
        - targetPort: 8000
          port: 80
          nodePort: 30001
    selector:
       name: dev
       app: flask-rest
