apiVersion: v1
kind: Service
metadata:
    name: prod-service

spec:
    type: ClusterIP
    ports:
        - targetPort: 8000
          port: 80
    selector:
       name: prod
       app: flask-rest

